// Psychiatric medicines database — condition-wise
// Each medicine: { name, brand, dose, class }

export const MEDICINES_BY_CONDITION = {
  "Insomnia": [
    { name: "Zolpidem", brand: "Stilnoct, Zolfresh, Nitrest, Sove", dose: "5mg, 10mg", class: "Hypnotic (Z-drug)" },
    { name: "Zopiclone", brand: "Zopicon, Somnil, Zpm", dose: "3.75mg, 7.5mg", class: "Hypnotic (Z-drug)" },
    { name: "Eszopiclone", brand: "Lunesta, Eszo, Esopic", dose: "1mg, 2mg, 3mg", class: "Hypnotic (Z-drug)" },
    { name: "Lemborexant", brand: "Dayvigo", dose: "5mg, 10mg", class: "Orexin antagonist (DORA)" },
    { name: "Suvorexant", brand: "Belsomra", dose: "5mg, 10mg, 15mg, 20mg", class: "Orexin antagonist (DORA)" },
    { name: "Daridorexant", brand: "Quviviq", dose: "25mg, 50mg", class: "Orexin antagonist (DORA)" },
    { name: "Ramelteon", brand: "Ramitax, Rozerem", dose: "8mg", class: "Melatonin agonist" },
    { name: "Melatonin", brand: "Meloset, Melogen, Sleepwell", dose: "3mg, 5mg, 10mg", class: "Melatonin" },
    { name: "Trazodone", brand: "Trazonil, Trazalon", dose: "25mg, 50mg, 100mg", class: "Atypical AD (sedating)" },
    { name: "Mirtazapine", brand: "Mirtaz, Mirnite, Remeron", dose: "7.5mg, 15mg, 30mg", class: "Atypical AD (sedating)" },
    { name: "Doxepin", brand: "Spectra, Silenor", dose: "3mg, 6mg, 10mg, 25mg", class: "TCA (low-dose sleep)" },
    { name: "Quetiapine", brand: "Qutipin, Quel", dose: "25mg, 50mg", class: "Atypical antipsychotic (off-label)" },
    { name: "Clonazepam", brand: "Rivotril, Lonazep, Zapiz", dose: "0.25mg, 0.5mg, 1mg", class: "Benzodiazepine" },
    { name: "Lorazepam", brand: "Ativan, Lorsedin", dose: "1mg, 2mg", class: "Benzodiazepine" },
    { name: "Etizolam", brand: "Etilaam, Etizola", dose: "0.25mg, 0.5mg, 1mg", class: "Benzodiazepine" },
    { name: "Nitrazepam", brand: "Nitravet, Sedamon", dose: "5mg, 10mg", class: "Benzodiazepine" },
    { name: "Diphenhydramine", brand: "Benadryl, Nytol", dose: "25mg, 50mg", class: "Antihistamine (OTC)" },
  ],

  "Migraine": [
    { name: "Sumatriptan", brand: "Suminat, Sumigra, Imitrex", dose: "25mg, 50mg, 100mg", class: "Triptan (abortive)" },
    { name: "Rizatriptan", brand: "Rizact, Maxalt", dose: "5mg, 10mg", class: "Triptan (abortive)" },
    { name: "Naratriptan", brand: "Naramig", dose: "1mg, 2.5mg", class: "Triptan (abortive)" },
    { name: "Zolmitriptan", brand: "Zolmist, Zomig", dose: "2.5mg, 5mg", class: "Triptan (abortive)" },
    { name: "Eletriptan", brand: "Relpax", dose: "20mg, 40mg", class: "Triptan (abortive)" },
    { name: "Ergotamine + Caffeine", brand: "Vasograin, Migranil", dose: "1mg + 100mg", class: "Ergot alkaloid" },
    { name: "Propranolol", brand: "Ciplar, Inderal, Provanol", dose: "10mg, 20mg, 40mg, 80mg", class: "Beta-blocker (prophylaxis)" },
    { name: "Flunarizine", brand: "Sibelium, Flunarin", dose: "5mg, 10mg", class: "Calcium blocker (prophylaxis)" },
    { name: "Topiramate", brand: "Topamac, Toprel", dose: "25mg, 50mg, 100mg", class: "Anticonvulsant (prophylaxis)" },
    { name: "Sodium Valproate", brand: "Encorate, Valprol", dose: "200mg, 300mg, 500mg CR", class: "Anticonvulsant (prophylaxis)" },
    { name: "Amitriptyline", brand: "Tryptomer", dose: "10mg, 25mg", class: "TCA (prophylaxis)" },
    { name: "Nortriptyline", brand: "Nortrip, Primox", dose: "10mg, 25mg", class: "TCA (prophylaxis)" },
    { name: "Venlafaxine", brand: "Veniz, Venlor", dose: "37.5mg, 75mg", class: "SNRI (prophylaxis)" },
    { name: "Erenumab", brand: "Aimovig", dose: "70mg, 140mg inj", class: "CGRP monoclonal antibody" },
    { name: "Galcanezumab", brand: "Emgality", dose: "120mg inj", class: "CGRP monoclonal antibody" },
    { name: "Fremanezumab", brand: "Ajovy", dose: "225mg inj", class: "CGRP monoclonal antibody" },
    { name: "Rimegepant", brand: "Nurtec ODT", dose: "75mg", class: "Gepant" },
    { name: "Ubrogepant", brand: "Ubrelvy", dose: "50mg, 100mg", class: "Gepant" },
  ],

  "Epilepsy": [
    { name: "Sodium Valproate", brand: "Encorate, Valprol, Valparin", dose: "200mg, 300mg, 500mg CR", class: "Broad-spectrum AED" },
    { name: "Divalproex", brand: "Valance, Divalid, Dicorate", dose: "250mg, 500mg, 750mg ER", class: "Broad-spectrum AED" },
    { name: "Carbamazepine", brand: "Tegrital, Mazetol, Zeptol", dose: "100mg, 200mg, 400mg CR", class: "Na-channel blocker" },
    { name: "Oxcarbazepine", brand: "Oxetol, Trioptal", dose: "150mg, 300mg, 600mg", class: "Na-channel blocker" },
    { name: "Phenytoin", brand: "Eptoin, Dilantin", dose: "50mg, 100mg, 300mg", class: "Na-channel blocker" },
    { name: "Phenobarbitone", brand: "Gardenal, Phenobarb", dose: "30mg, 60mg, 100mg", class: "Barbiturate" },
    { name: "Lamotrigine", brand: "Lamitor, Lametec, Lamepil", dose: "25mg, 50mg, 100mg, 200mg", class: "Na-channel blocker" },
    { name: "Levetiracetam", brand: "Levipil, Torleva, Keppra", dose: "250mg, 500mg, 750mg, 1000mg", class: "SV2A modulator" },
    { name: "Topiramate", brand: "Topamac, Toprel", dose: "25mg, 50mg, 100mg", class: "Multi-mechanism AED" },
    { name: "Clobazam", brand: "Frisium, Cloba", dose: "5mg, 10mg, 20mg", class: "Benzodiazepine" },
    { name: "Clonazepam", brand: "Rivotril, Lonazep", dose: "0.25mg, 0.5mg, 1mg, 2mg", class: "Benzodiazepine" },
    { name: "Gabapentin", brand: "Gabantin, Gabapin", dose: "100mg, 300mg, 400mg", class: "Calcium channel ligand" },
    { name: "Pregabalin", brand: "Lyrica, Pregeb, Nervup", dose: "25mg, 50mg, 75mg, 150mg", class: "Calcium channel ligand" },
    { name: "Lacosamide", brand: "Lacosam, Vimpat", dose: "50mg, 100mg, 150mg, 200mg", class: "Na-channel (slow)" },
    { name: "Perampanel", brand: "Fycompa", dose: "2mg, 4mg, 6mg, 8mg", class: "AMPA antagonist" },
    { name: "Brivaracetam", brand: "Briviact", dose: "25mg, 50mg, 100mg", class: "SV2A modulator" },
    { name: "Zonisamide", brand: "Zonisep, Zonegran", dose: "25mg, 50mg, 100mg", class: "Multi-mechanism AED" },
    { name: "Ethosuximide", brand: "Zarontin", dose: "250mg", class: "T-type Ca blocker (absence)" },
    { name: "Vigabatrin", brand: "Sabril", dose: "500mg", class: "GABA transaminase inhibitor" },
  ],

  "Depression": [
    { name: "Escitalopram", brand: "Nexito, Stalopam, Szetalo, Cilentra, Rexipra, Lexapro", dose: "5mg, 10mg, 15mg, 20mg", class: "SSRI" },
    { name: "Sertraline", brand: "Daxid, Serlift, Serta, Zoloft, Sertima", dose: "25mg, 50mg, 100mg, 150mg, 200mg", class: "SSRI" },
    { name: "Fluoxetine", brand: "Fludac, Prodep, Flunil, Prozac, Nuzak", dose: "10mg, 20mg, 40mg, 60mg", class: "SSRI" },
    { name: "Paroxetine", brand: "Paxidep, Xet, Pari, Pexep, Paxil", dose: "10mg, 12.5mg CR, 20mg, 25mg CR, 37.5mg CR", class: "SSRI" },
    { name: "Fluvoxamine", brand: "Fluvoxin, Voxamin, Faverin", dose: "50mg, 100mg", class: "SSRI" },
    { name: "Citalopram", brand: "Citalop, Cipram, Celepra", dose: "10mg, 20mg, 40mg", class: "SSRI" },
    { name: "Venlafaxine", brand: "Veniz, Venlor, Ventab, Effexor", dose: "37.5mg, 75mg, 150mg XR", class: "SNRI" },
    { name: "Desvenlafaxine", brand: "Dvenlax, Desval, Pristiq", dose: "50mg, 100mg", class: "SNRI" },
    { name: "Duloxetine", brand: "Dulane, Duzela, Duvanta, Cymbalta", dose: "20mg, 30mg, 60mg, 90mg", class: "SNRI" },
    { name: "Milnacipran", brand: "Mcipran, Milcep, Ixel", dose: "25mg, 50mg, 100mg", class: "SNRI" },
    { name: "Levomilnacipran", brand: "Fetzima", dose: "20mg, 40mg, 80mg, 120mg", class: "SNRI" },
    { name: "Mirtazapine", brand: "Mirtaz, Mirnite, Remeron", dose: "7.5mg, 15mg, 30mg, 45mg", class: "NaSSA" },
    { name: "Bupropion", brand: "Bupron SR, Bupron XL, Wellbutrin", dose: "150mg SR, 300mg SR, 300mg XL", class: "NDRI" },
    { name: "Trazodone", brand: "Trazonil, Trazalon", dose: "25mg, 50mg, 100mg, 150mg", class: "SARI" },
    { name: "Vortioxetine", brand: "Brintellix, Vortisol, Trintellix", dose: "5mg, 10mg, 20mg", class: "Serotonin modulator" },
    { name: "Vilazodone", brand: "Viibryd", dose: "10mg, 20mg, 40mg", class: "SSRI + 5-HT1A partial agonist" },
    { name: "Agomelatine", brand: "Valdoxan, Agotine, Melixir", dose: "25mg, 50mg", class: "Melatonin agonist" },
    { name: "Tianeptine", brand: "Stablon, Tianept", dose: "12.5mg, 37.5mg SR", class: "Atypical AD" },
    { name: "Amitriptyline", brand: "Tryptomer, Amitor", dose: "10mg, 25mg, 50mg, 75mg", class: "TCA" },
    { name: "Imipramine", brand: "Depsonil, Antidep", dose: "25mg, 50mg, 75mg", class: "TCA" },
    { name: "Nortriptyline", brand: "Nortrip, Primox", dose: "10mg, 25mg, 50mg", class: "TCA" },
    { name: "Dothiepin", brand: "Prothiaden, Depnil", dose: "25mg, 50mg, 75mg", class: "TCA" },
    { name: "Moclobemide", brand: "Rimarex, Aurorix", dose: "150mg, 300mg", class: "RIMA (MAOI)" },
    { name: "Esketamine (intranasal)", brand: "Spravato", dose: "28mg, 56mg, 84mg spray", class: "NMDA antagonist (TRD)" },
    { name: "Brexanolone", brand: "Zulresso", dose: "IV infusion", class: "GABA-A modulator (postpartum)" },
    { name: "Dextromethorphan + Bupropion", brand: "Auvelity", dose: "45mg/105mg", class: "NMDA + NDRI" },
  ],

  "Anxiety": [
    { name: "Escitalopram", brand: "Nexito, Stalopam, Cilentra", dose: "5mg, 10mg, 20mg", class: "SSRI" },
    { name: "Sertraline", brand: "Daxid, Serlift, Zoloft", dose: "25mg, 50mg, 100mg", class: "SSRI" },
    { name: "Paroxetine", brand: "Paxidep, Xet, Pexep", dose: "12.5mg CR, 25mg CR", class: "SSRI" },
    { name: "Fluvoxamine", brand: "Fluvoxin, Voxamin", dose: "50mg, 100mg", class: "SSRI" },
    { name: "Venlafaxine", brand: "Veniz, Venlor XR", dose: "37.5mg, 75mg, 150mg XR", class: "SNRI" },
    { name: "Duloxetine", brand: "Dulane, Duzela", dose: "20mg, 30mg, 60mg", class: "SNRI" },
    { name: "Clonazepam", brand: "Rivotril, Lonazep, Zapiz", dose: "0.25mg, 0.5mg, 1mg, 2mg", class: "Benzodiazepine" },
    { name: "Alprazolam", brand: "Restyl, Alprax, Alzolam", dose: "0.25mg, 0.5mg, 1mg", class: "Benzodiazepine" },
    { name: "Lorazepam", brand: "Ativan, Lorsedin, Trapex", dose: "1mg, 2mg", class: "Benzodiazepine" },
    { name: "Diazepam", brand: "Valium, Calmpose", dose: "2mg, 5mg, 10mg", class: "Benzodiazepine" },
    { name: "Etizolam", brand: "Etilaam, Etizola", dose: "0.25mg, 0.5mg, 1mg", class: "Benzodiazepine" },
    { name: "Chlordiazepoxide", brand: "Librium, Equirex", dose: "10mg, 25mg", class: "Benzodiazepine" },
    { name: "Buspirone", brand: "Buspin, Anxipar", dose: "5mg, 10mg, 15mg", class: "5-HT1A partial agonist" },
    { name: "Pregabalin", brand: "Lyrica, Pregeb, Nervup", dose: "25mg, 50mg, 75mg, 150mg", class: "Calcium channel ligand" },
    { name: "Gabapentin", brand: "Gabantin, Gabapin", dose: "100mg, 300mg, 400mg", class: "Calcium channel ligand" },
    { name: "Propranolol", brand: "Ciplar, Inderal, Provanol", dose: "10mg, 20mg, 40mg", class: "Beta-blocker (performance anxiety)" },
    { name: "Hydroxyzine", brand: "Atarax", dose: "10mg, 25mg", class: "Antihistamine anxiolytic" },
  ],

  "Bipolar": [
    { name: "Lithium Carbonate", brand: "Lithosun, Licab, Intalith", dose: "300mg, 400mg SR", class: "Mood stabilizer" },
    { name: "Sodium Valproate", brand: "Encorate, Valprol, Valparin", dose: "200mg, 300mg, 500mg CR", class: "Mood stabilizer" },
    { name: "Divalproex", brand: "Valance, Divalid, Dicorate", dose: "250mg, 500mg, 750mg ER", class: "Mood stabilizer" },
    { name: "Lamotrigine", brand: "Lamitor, Lametec, Lamepil", dose: "25mg, 50mg, 100mg, 200mg", class: "Mood stabilizer (depression phase)" },
    { name: "Carbamazepine", brand: "Tegrital, Mazetol, Zeptol", dose: "200mg, 400mg CR", class: "Mood stabilizer" },
    { name: "Oxcarbazepine", brand: "Oxetol, Trioptal", dose: "300mg, 600mg", class: "Mood stabilizer" },
    { name: "Olanzapine", brand: "Oleanz, Olimelt, Zyprexa", dose: "2.5mg, 5mg, 10mg, 15mg, 20mg", class: "Atypical antipsychotic" },
    { name: "Quetiapine", brand: "Qutipin, Quel, Seroquel", dose: "100mg, 200mg, 300mg, 400mg XR", class: "Atypical antipsychotic" },
    { name: "Risperidone", brand: "Risdone, Sizodon, Risperdal", dose: "1mg, 2mg, 3mg, 4mg", class: "Atypical antipsychotic" },
    { name: "Aripiprazole", brand: "Asprito, Arpizol, Abilify", dose: "5mg, 10mg, 15mg, 20mg, 30mg", class: "Atypical antipsychotic" },
    { name: "Lurasidone", brand: "Latuda, Lurace", dose: "20mg, 40mg, 60mg, 80mg", class: "Atypical antipsychotic" },
    { name: "Asenapine", brand: "Saphris, Asnapin", dose: "5mg, 10mg SL", class: "Atypical antipsychotic" },
    { name: "Cariprazine", brand: "Vraylar, Carip", dose: "1.5mg, 3mg, 4.5mg, 6mg", class: "Atypical antipsychotic" },
    { name: "Olanzapine + Fluoxetine", brand: "Symbyax", dose: "3/25mg, 6/25mg, 12/50mg", class: "Bipolar depression combo" },
  ],

  "Schizophrenia": [
    { name: "Olanzapine", brand: "Oleanz, Olimelt, Ozapine, Zyprexa", dose: "2.5mg, 5mg, 10mg, 15mg, 20mg", class: "Atypical antipsychotic" },
    { name: "Risperidone", brand: "Risdone, Sizodon, Respidon, Risperdal", dose: "0.25mg, 0.5mg, 1mg, 2mg, 3mg, 4mg", class: "Atypical antipsychotic" },
    { name: "Quetiapine", brand: "Qutipin, Quel, Seroquel", dose: "25mg, 50mg, 100mg, 200mg, 300mg, 400mg XR", class: "Atypical antipsychotic" },
    { name: "Aripiprazole", brand: "Asprito, Arpizol, Abilify", dose: "5mg, 10mg, 15mg, 20mg, 30mg", class: "Atypical antipsychotic" },
    { name: "Amisulpride", brand: "Solian, Amisulide", dose: "50mg, 100mg, 200mg, 400mg", class: "Atypical antipsychotic" },
    { name: "Clozapine", brand: "Sizopin, Skizoril, Clozapex", dose: "25mg, 50mg, 100mg, 200mg", class: "Atypical (TRS)" },
    { name: "Paliperidone", brand: "Invega, Paliris", dose: "3mg, 6mg, 9mg ER", class: "Atypical antipsychotic" },
    { name: "Lurasidone", brand: "Latuda, Lurace", dose: "20mg, 40mg, 80mg, 120mg", class: "Atypical antipsychotic" },
    { name: "Ziprasidone", brand: "Zipsydon, Geodon", dose: "20mg, 40mg, 60mg, 80mg", class: "Atypical antipsychotic" },
    { name: "Asenapine", brand: "Saphris, Asnapin", dose: "5mg, 10mg SL", class: "Atypical antipsychotic" },
    { name: "Iloperidone", brand: "Fanapt, Ilop", dose: "1mg, 2mg, 4mg, 6mg, 8mg, 12mg", class: "Atypical antipsychotic" },
    { name: "Brexpiprazole", brand: "Rexulti", dose: "0.5mg, 1mg, 2mg, 3mg, 4mg", class: "Atypical antipsychotic" },
    { name: "Cariprazine", brand: "Vraylar, Carip", dose: "1.5mg, 3mg, 4.5mg, 6mg", class: "Atypical antipsychotic" },
    { name: "Lumateperone", brand: "Caplyta", dose: "42mg", class: "Atypical antipsychotic" },
    { name: "Haloperidol", brand: "Serenace, Halidol, Haldol", dose: "0.5mg, 1.5mg, 5mg, 10mg, 20mg", class: "Typical antipsychotic" },
    { name: "Chlorpromazine", brand: "Megatil, Sun Prazin, Largactil", dose: "25mg, 50mg, 100mg, 200mg", class: "Typical antipsychotic" },
    { name: "Trifluoperazine", brand: "Espazine, Trinicalm, Stelazine", dose: "1mg, 2mg, 5mg, 10mg", class: "Typical antipsychotic" },
    { name: "Flupenthixol", brand: "Fluanxol, Flupen", dose: "0.5mg, 1mg, 3mg", class: "Typical antipsychotic" },
    { name: "Fluphenazine", brand: "Prolinate, Anatensol", dose: "1mg, 2.5mg, 5mg", class: "Typical antipsychotic" },
    { name: "Pimozide", brand: "Mozep, Larap, Orap", dose: "2mg, 4mg", class: "Typical antipsychotic" },
    { name: "Sulpiride", brand: "Sulpitac, Norsul", dose: "50mg, 100mg, 200mg", class: "Typical antipsychotic" },
    { name: "Loxapine", brand: "Loxapac, Adasuve", dose: "10mg, 25mg, 50mg", class: "Typical antipsychotic" },
    { name: "Haloperidol Decanoate", brand: "Senorm-LA, Haldol Dec", dose: "50mg/ml, 100mg/ml inj", class: "LAI (typical)" },
    { name: "Flupenthixol Decanoate", brand: "Fluanxol Depot", dose: "20mg/ml inj", class: "LAI (typical)" },
    { name: "Risperidone LAI", brand: "Risperdal Consta", dose: "25mg, 37.5mg, 50mg inj", class: "LAI (atypical)" },
    { name: "Paliperidone Palmitate", brand: "Invega Sustenna, Invega Trinza", dose: "78-234mg monthly inj", class: "LAI (atypical)" },
    { name: "Aripiprazole LAI", brand: "Abilify Maintena", dose: "300mg, 400mg inj", class: "LAI (atypical)" },
    { name: "Olanzapine Pamoate", brand: "Zyprexa Relprevv", dose: "210mg, 300mg, 405mg inj", class: "LAI (atypical)" },
    { name: "Trihexyphenidyl", brand: "Pacitane, Parkin", dose: "2mg, 5mg", class: "Anticholinergic (EPS)" },
    { name: "Benztropine", brand: "Cogentin", dose: "0.5mg, 1mg, 2mg", class: "Anticholinergic (EPS)" },
    { name: "Propranolol", brand: "Ciplar", dose: "10mg, 20mg, 40mg", class: "Beta-blocker (akathisia)" },
  ],

  "OCD": [
    { name: "Fluoxetine", brand: "Fludac, Prodep, Flunil, Prozac", dose: "20mg, 40mg, 60mg, 80mg", class: "SSRI (high-dose)" },
    { name: "Fluvoxamine", brand: "Fluvoxin, Voxamin, Faverin", dose: "100mg, 200mg, 300mg", class: "SSRI (high-dose)" },
    { name: "Sertraline", brand: "Daxid, Serlift, Zoloft", dose: "100mg, 150mg, 200mg", class: "SSRI (high-dose)" },
    { name: "Paroxetine", brand: "Paxidep, Xet, Pexep", dose: "40mg, 60mg", class: "SSRI (high-dose)" },
    { name: "Escitalopram", brand: "Nexito, Stalopam", dose: "20mg, 30mg", class: "SSRI (high-dose)" },
    { name: "Citalopram", brand: "Citalop, Cipram", dose: "40mg, 60mg", class: "SSRI (high-dose)" },
    { name: "Clomipramine", brand: "Anafranil, Clofranil, Clonil", dose: "25mg, 50mg, 75mg, 100mg", class: "TCA (gold standard OCD)" },
    { name: "Venlafaxine", brand: "Veniz, Venlor XR", dose: "150mg, 225mg XR", class: "SNRI (off-label)" },
    { name: "Risperidone", brand: "Risdone, Sizodon", dose: "0.5mg, 1mg, 2mg", class: "Augmentation (treatment-resistant)" },
    { name: "Aripiprazole", brand: "Asprito, Arpizol", dose: "5mg, 10mg, 15mg", class: "Augmentation" },
    { name: "Olanzapine", brand: "Oleanz", dose: "2.5mg, 5mg", class: "Augmentation" },
    { name: "Quetiapine", brand: "Qutipin", dose: "50mg, 100mg", class: "Augmentation" },
    { name: "N-Acetylcysteine", brand: "Mucomix, NAC", dose: "600mg, 1200mg", class: "Glutamate modulator (adjunct)" },
    { name: "Memantine", brand: "Admenta, Nemdaa", dose: "5mg, 10mg", class: "NMDA antagonist (adjunct)" },
  ],

  "ADHD": [
    { name: "Methylphenidate", brand: "Inspiral, Addwize, Ritalin, Concerta", dose: "5mg, 10mg, 18mg, 27mg, 36mg, 54mg ER", class: "Stimulant" },
    { name: "Dexmethylphenidate", brand: "Focalin", dose: "2.5mg, 5mg, 10mg", class: "Stimulant" },
    { name: "Dextroamphetamine", brand: "Dexedrine", dose: "5mg, 10mg, 15mg", class: "Stimulant" },
    { name: "Mixed Amphetamine Salts", brand: "Adderall, Adderall XR", dose: "5mg, 10mg, 20mg, 30mg", class: "Stimulant" },
    { name: "Lisdexamfetamine", brand: "Vyvanse", dose: "30mg, 50mg, 70mg", class: "Stimulant (prodrug)" },
    { name: "Atomoxetine", brand: "Attentin, Attentrol, Strattera", dose: "10mg, 18mg, 25mg, 40mg, 60mg, 80mg, 100mg", class: "Non-stimulant (NRI)" },
    { name: "Guanfacine ER", brand: "Intuniv", dose: "1mg, 2mg, 3mg, 4mg", class: "Alpha-2 agonist" },
    { name: "Clonidine ER", brand: "Kapvay, Catapres", dose: "0.1mg, 0.2mg, 0.3mg", class: "Alpha-2 agonist" },
    { name: "Viloxazine ER", brand: "Qelbree", dose: "100mg, 150mg, 200mg", class: "Non-stimulant (SNRI)" },
    { name: "Modafinil", brand: "Modalert, Provigil, Modapro", dose: "100mg, 200mg", class: "Wakefulness agent (off-label)" },
    { name: "Armodafinil", brand: "Waklert, Armod", dose: "50mg, 150mg, 250mg", class: "Wakefulness agent (off-label)" },
    { name: "Bupropion", brand: "Bupron SR, Bupron XL", dose: "150mg, 300mg SR/XL", class: "NDRI (off-label)" },
  ],

  "PTSD": [
    { name: "Sertraline", brand: "Daxid, Serlift, Zoloft", dose: "50mg, 100mg, 200mg", class: "SSRI (FDA approved)" },
    { name: "Paroxetine", brand: "Paxidep, Xet, Pexep", dose: "20mg, 40mg, 60mg", class: "SSRI (FDA approved)" },
    { name: "Fluoxetine", brand: "Fludac, Prodep", dose: "20mg, 40mg, 60mg", class: "SSRI" },
    { name: "Venlafaxine XR", brand: "Veniz, Venlor XR", dose: "75mg, 150mg, 225mg XR", class: "SNRI" },
    { name: "Prazosin", brand: "Prazopress, Minipress", dose: "1mg, 2mg, 5mg", class: "Alpha-1 blocker (nightmares)" },
    { name: "Topiramate", brand: "Topamac", dose: "50mg, 100mg, 200mg", class: "Anticonvulsant (adjunct)" },
    { name: "Risperidone", brand: "Risdone, Sizodon", dose: "0.5mg, 1mg, 2mg", class: "Augmentation" },
    { name: "Quetiapine", brand: "Qutipin", dose: "50mg, 100mg, 200mg", class: "Augmentation" },
    { name: "Mirtazapine", brand: "Mirtaz, Mirnite", dose: "15mg, 30mg", class: "NaSSA (sleep+mood)" },
    { name: "Clonidine", brand: "Catapres, Clodapres", dose: "0.1mg, 0.2mg", class: "Alpha-2 agonist" },
    { name: "Propranolol", brand: "Ciplar, Inderal", dose: "10mg, 20mg, 40mg", class: "Beta-blocker (adjunct)" },
    { name: "MDMA-assisted therapy", brand: "(investigational)", dose: "80-120mg (clinical)", class: "Entactogen (research)" },
  ],

  "De-addiction": [
    { name: "Naltrexone", brand: "Nodict, Naltima", dose: "50mg", class: "Opioid antagonist (alcohol/opioid)" },
    { name: "Naltrexone LAI", brand: "Vivitrol", dose: "380mg IM monthly", class: "Opioid antagonist (LAI)" },
    { name: "Acamprosate", brand: "Acamprol, Campral", dose: "333mg, 666mg", class: "Anti-craving (alcohol)" },
    { name: "Disulfiram", brand: "Dizone, Esperal, Antabuse", dose: "250mg, 500mg", class: "Aversive (alcohol)" },
    { name: "Baclofen", brand: "Lioresal, Baclofar", dose: "10mg, 20mg, 30mg", class: "GABA-B agonist (alcohol off-label)" },
    { name: "Topiramate", brand: "Topamac, Toprel", dose: "25mg, 50mg, 100mg, 200mg", class: "Anticonvulsant (alcohol off-label)" },
    { name: "Gabapentin", brand: "Gabantin, Gabapin", dose: "300mg, 600mg, 900mg", class: "Off-label (alcohol)" },
    { name: "Bupropion SR", brand: "Bupron SR, Zyban", dose: "150mg SR", class: "Smoking cessation" },
    { name: "Varenicline", brand: "Champix, Chantix", dose: "0.5mg, 1mg", class: "Smoking cessation" },
    { name: "Nicotine Replacement", brand: "Nicotex, Nicorette gum/patch", dose: "2mg, 4mg gum; 7-21mg patch", class: "Smoking cessation" },
    { name: "Buprenorphine", brand: "Addnok, Subutex, Suboxone", dose: "2mg, 8mg SL", class: "Opioid partial agonist (OMT)" },
    { name: "Buprenorphine + Naloxone", brand: "Suboxone, Addnok-N", dose: "2/0.5mg, 8/2mg", class: "Opioid MAT" },
    { name: "Methadone", brand: "Methadose, Dolophine", dose: "5mg, 10mg, 40mg", class: "Opioid agonist (OMT)" },
    { name: "Clonidine", brand: "Catapres, Clodapres", dose: "0.1mg, 0.2mg", class: "Opioid withdrawal" },
    { name: "Lofexidine", brand: "Lucemyra", dose: "0.18mg", class: "Opioid withdrawal" },
    { name: "Chlordiazepoxide", brand: "Librium, Equirex", dose: "10mg, 25mg", class: "Alcohol withdrawal" },
    { name: "Diazepam", brand: "Valium, Calmpose", dose: "5mg, 10mg", class: "Alcohol withdrawal" },
    { name: "Thiamine", brand: "Benalgis, Benfomet", dose: "100mg, 200mg", class: "Wernicke prevention" },
  ],

  "Sexual Health - Low Libido": [
    { name: "Bupropion", brand: "Bupron SR, Bupron XL, Wellbutrin", dose: "150mg SR, 300mg XL", class: "NDRI (off-label libido)" },
    { name: "Buspirone", brand: "Buspin, Anxipar", dose: "10mg, 15mg, 30mg", class: "5-HT1A (off-label libido)" },
    { name: "Flibanserin", brand: "Addyi", dose: "100mg HS", class: "5-HT1A agonist/2A antagonist (female HSDD)" },
    { name: "Bremelanotide", brand: "Vyleesi", dose: "1.75mg SC inj", class: "Melanocortin agonist (female HSDD)" },
    { name: "Testosterone (transdermal)", brand: "Androgel, Testogel, Axiron", dose: "1%, 2% gel", class: "Androgen (male/female)" },
    { name: "Testosterone Undecanoate", brand: "Nebido, Andriol", dose: "40mg cap; 1000mg inj", class: "Androgen oral/inj" },
    { name: "DHEA", brand: "DHEA supplement", dose: "25mg, 50mg", class: "Adrenal androgen (adjunct)" },
    { name: "Trazodone", brand: "Trazonil", dose: "50mg, 100mg", class: "Off-label (SSRI-induced dysfunction)" },
    { name: "Yohimbine", brand: "Yohimbe", dose: "5mg, 10mg", class: "Alpha-2 antagonist (off-label)" },
    { name: "Ospemifene", brand: "Osphena", dose: "60mg", class: "SERM (dyspareunia postmenopausal)" },
  ],

  "Sexual Health - Erectile Dysfunction": [
    { name: "Sildenafil", brand: "Viagra, Penegra, Suhagra, Silagra", dose: "25mg, 50mg, 100mg", class: "PDE5 inhibitor" },
    { name: "Tadalafil", brand: "Cialis, Tadacip, Megalis, Tadarise", dose: "2.5mg, 5mg, 10mg, 20mg", class: "PDE5 inhibitor (long-acting)" },
    { name: "Vardenafil", brand: "Levitra, Vivanza", dose: "5mg, 10mg, 20mg", class: "PDE5 inhibitor" },
    { name: "Avanafil", brand: "Stendra, Spedra", dose: "50mg, 100mg, 200mg", class: "PDE5 inhibitor (fast-onset)" },
    { name: "Udenafil", brand: "Zydena", dose: "100mg, 200mg", class: "PDE5 inhibitor" },
    { name: "Alprostadil", brand: "Caverject, Muse", dose: "5-40mcg inj; 125-1000mcg urethral", class: "Prostaglandin E1" },
    { name: "Testosterone (if low)", brand: "Nebido, Andriol, Sustanon", dose: "various", class: "Androgen replacement" },
  ],

  "Sexual Health - Premature Ejaculation": [
    { name: "Dapoxetine", brand: "Duralast, Priligy, Poxet", dose: "30mg, 60mg", class: "Short-acting SSRI (PE)" },
    { name: "Paroxetine", brand: "Paxidep, Xet", dose: "10mg, 20mg", class: "SSRI (off-label PE)" },
    { name: "Sertraline", brand: "Daxid, Serlift", dose: "25mg, 50mg", class: "SSRI (off-label PE)" },
    { name: "Fluoxetine", brand: "Fludac, Prodep", dose: "20mg", class: "SSRI (off-label PE)" },
    { name: "Clomipramine", brand: "Anafranil, Clofranil", dose: "10mg, 25mg", class: "TCA (off-label PE)" },
    { name: "Lidocaine-Prilocaine spray", brand: "Stud 5000, Promescent, EMLA", dose: "Topical spray/cream", class: "Topical anesthetic" },
    { name: "Tramadol", brand: "Ultracet, Tramacip", dose: "50mg, 100mg PRN", class: "Opioid (off-label PE)" },
  ],

  "Dementia": [
    { name: "Donepezil", brand: "Aricep, Donep, Admenta", dose: "5mg, 10mg, 23mg", class: "Cholinesterase inhibitor" },
    { name: "Rivastigmine", brand: "Exelon, Rivamer", dose: "1.5mg, 3mg, 4.5mg, 6mg; 4.6, 9.5, 13.3mg patch", class: "Cholinesterase inhibitor" },
    { name: "Galantamine", brand: "Razadyne, Reminyl", dose: "8mg, 16mg, 24mg ER", class: "Cholinesterase inhibitor" },
    { name: "Memantine", brand: "Admenta, Nemdaa, Namenda", dose: "5mg, 10mg, 20mg", class: "NMDA antagonist" },
    { name: "Donepezil + Memantine", brand: "Namzaric", dose: "10/14mg, 10/28mg", class: "Combination" },
    { name: "Aducanumab", brand: "Aduhelm", dose: "IV infusion", class: "Anti-amyloid Ab (Alzheimer)" },
    { name: "Lecanemab", brand: "Leqembi", dose: "IV infusion", class: "Anti-amyloid Ab (Alzheimer)" },
    { name: "Risperidone", brand: "Risdone", dose: "0.25mg, 0.5mg", class: "BPSD (caution)" },
    { name: "Quetiapine", brand: "Qutipin", dose: "25mg, 50mg", class: "BPSD (caution)" },
    { name: "Trazodone", brand: "Trazonil", dose: "25mg, 50mg", class: "Agitation/sleep" },
  ],
};

export const CONDITIONS = Object.keys(MEDICINES_BY_CONDITION);